export const ADD_MOVIE_LIST = "ADD_MOVIE_LIST";

export const MODAL_OPEN_STATUS = "MODAL_OPEN_STATUS";

export const CLEAR_MOVIE_LIST = "CLEAR_MOVIE_LIST";

export const SEARCH_KEY_INSERT = "SEARCH_KEY_INSERT";

export const PAGE_NO_UPDATE = "PAGE_NO_UPDATE";

export const MOVIE_RESPONSE_STATUS = "MOVIE_RESPONSE_STATUS";

export const SELECTED_MOVIE_DETAILS = "SELECTED_MOVIE_DETAILS";
